---
kind: pipeline
type: docker
name: 'compile and test C# CLI app'
steps:
  - name: compile and test (mono)
    image: mono:6
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    commands:
      - apt update; apt install build-essential icu-devtools locales -y
      - sed -i "/$${LANG}/s/^# //g" /etc/locale.gen && locale-gen
      - icuinfo
      - make test
